

filter_list =              ["//android.widget.TextView[@text='H1']", "//android.widget.TextView[@text='H2']",
                            "//android.widget.TextView[@text='H3']", "//android.widget.TextView[@text='F1']",
                            "//android.widget.TextView[@text='F2']", "//android.widget.TextView[@text='RADIO']",
                            "//android.widget.TextView[@text='F3']", "//android.widget.TextView[@text='A1']",
                            "//android.widget.TextView[@text='A2']", "//android.widget.TextView[@text='A3']",
                            "//android.widget.TextView[@text='R1']", "//android.widget.TextView[@text='R2']",
                            "//android.widget.TextView[@text='R3']", "//android.widget.TextView[@text='V1']",
                            "//android.widget.TextView[@text='V2']", "//android.widget.TextView[@text='V3']",
                            "//android.widget.TextView[@text='KOTO']", "//android.widget.TextView[@text='PIKE']",
                            "//android.widget.TextView[@text='CALICO']", "//android.widget.TextView[@text='TARIUS']",
                            "//android.widget.TextView[@text='ROSE']", "//android.widget.TextView[@text='BACH']",
                            "//android.widget.TextView[@text='LOFT']", "//android.widget.TextView[@text='JUKE']",
                            "//android.widget.TextView[@text='OSAKA']", "//android.widget.TextView[@text='KAUAI']",
                            "//android.widget.TextView[@text='COAST']", "//android.widget.TextView[@text='TIKI']",
                            "//android.widget.TextView[@text='OAK']", "//android.widget.TextView[@text='TOKYO']",
                            "//android.widget.TextView[@text='BARK']", "//android.widget.TextView[@text='LINCOLN']",
                            "//android.widget.TextView[@text='1989']", "//android.widget.TextView[@text='HIRO']",
                            "//android.widget.TextView[@text='HULA']", "//android.widget.TextView[@text='WAVES']",
                            "//android.widget.TextView[@text='KAYAK']", "//android.widget.TextView[@text='RIO']",
                            "//android.widget.TextView[@text='NEWPORT']", "//android.widget.TextView[@text='NOVA']",
                            "//android.widget.TextView[@text='WASATCH']", "//android.widget.TextView[@text='MARKET']",
                            "//android.widget.TextView[@text='MADRID']", "//android.widget.TextView[@text='FLUX']",
                            "//android.widget.TextView[@text='PETRA']", "//android.widget.TextView[@text='CELSIUS']",
                            "//android.widget.TextView[@text='ORGANIC']", "//android.widget.TextView[@text='NOMAD']",
                            "//android.widget.TextView[@text='ALTA']", "//android.widget.TextView[@text='BALTIC']",
                            "//android.widget.TextView[@text='JUNO']", "//android.widget.TextView[@text='ATHENS']",
                            "//android.widget.TextView[@text='C1']", "//android.widget.TextView[@text='C2']",
                            "//android.widget.TextView[@text='C3']", "//android.widget.TextView[@text='B1']",
                            "//android.widget.TextView[@text='B2']", "//android.widget.TextView[@text='B3']",
                            "//android.widget.TextView[@text='D1']", "//android.widget.TextView[@text='D2']",
                            "//android.widget.TextView[@text='D3']", "//android.widget.TextView[@text='E1']",
                            "//android.widget.TextView[@text='E2']", "//android.widget.TextView[@text='E3']",
                            "//android.widget.TextView[@text='G1']", "//android.widget.TextView[@text='G2']",
                            "//android.widget.TextView[@text='G3']", "//android.widget.TextView[@text='J1']",
                            "//android.widget.TextView[@text='J2']", "//android.widget.TextView[@text='J3']",
                            "//android.widget.TextView[@text='K1']", "//android.widget.TextView[@text='K2']",
                            "//android.widget.TextView[@text='K3']", "//android.widget.TextView[@text='L1']",
                            "//android.widget.TextView[@text='L2']", "//android.widget.TextView[@text='L3']",
                            "//android.widget.TextView[@text='M1']", "//android.widget.TextView[@text='M2']",
                            "//android.widget.TextView[@text='M3']", "//android.widget.TextView[@text='N1']",
                            "//android.widget.TextView[@text='N2']", "//android.widget.TextView[@text='N3']",
                            "//android.widget.TextView[@text='P1']", "//android.widget.TextView[@text='P2']",
                            "//android.widget.TextView[@text='P3']"]


filter_manager_list =       ["//android.widget.TextView[@text='ATHENS']", "//android.widget.TextView[@text='NOVA']",
                             "//android.widget.TextView[@text='KAYAK']", "//android.widget.TextView[@text='MARKET']",
                             "//android.widget.TextView[@text='WAVES']", "//android.widget.TextView[@text='NEWPORT']",
                             "//android.widget.TextView[@text='FLUX']", "//android.widget.TextView[@text='BALTIC']",
                             "//android.widget.TextView[@text='CELSIUS']"]

cropFeatureList =         ["//android.widget.TextView[@text ='FREE']", "//android.widget.TextView[@text ='1:1']",
                           "//android.widget.TextView[@text ='3:2']", "//android.widget.TextView[@text ='5:3']",
                           "//android.widget.TextView[@text ='4:3']", "//android.widget.TextView[@text ='5:4']",
                           "//android.widget.TextView[@text ='4:5']", "//android.widget.TextView[@text ='3:4']",
                           "//android.widget.TextView[@text ='2:3']", "//android.widget.TextView[@text ='7:5']",
                           "//android.widget.TextView[@text ='21:9']"]

border_list =            ["//android.widget.TextView[@text='MARBLE']", "//android.widget.TextView[@text='XOXO']",
                          "//android.widget.TextView[@text='COLOR']", "//android.widget.TextView[@text='MERICA']",
                          "//android.widget.TextView[@text='VIBES']", "//android.widget.TextView[@text='SPRING']",
                          "//android.widget.TextView[@text='HOLIDAY']", "//android.widget.TextView[@text='AUTUMN']",
                          "//android.widget.TextView[@text='WOOD']", "//android.widget.TextView[@text='FLORAL']",
                          "//android.widget.TextView[@text='COSMIC']", "//android.widget.TextView[@text='CAMO']",
                          "//android.widget.TextView[@text='BW I']", "//android.widget.TextView[@text='POLKA DOT']",
                          "//android.widget.TextView[@text='BW II']", "//android.widget.TextView[@text='ANIMAL']",
                          "//android.widget.TextView[@text='NEBULA']", "//android.widget.TextView[@text='CHEVRON']",
                          "//android.widget.TextView[@text='TIMBER']", "//android.widget.TextView[@text='GC']",
                          "//android.widget.TextView[@text='BW III']", "//android.widget.TextView[@text='GOLD']",
                          "//android.widget.TextView[@text='GLITTER']", "//android.widget.TextView[@text='GEOMETRIC']",
                          "//android.widget.TextView[@text='LINE']", "//android.widget.TextView[@text='TRIBAL']",
                          "//android.widget.TextView[@text='PINK']"]

adjustmentsList =         ["//android.widget.TextView[@text ='CONTRAST']",
                           "//android.widget.TextView[@text ='EXPOSURE']",
                           "//android.widget.TextView[@text ='BRIGHTNESS']",
                           "//android.widget.TextView[@text ='SHARPNESS']",
                           "//android.widget.TextView[@text ='SATURATION']",
                           "//android.widget.TextView[@text ='TINT']",
                           "//android.widget.TextView[@text ='WARMTH']",
                           "//android.widget.TextView[@text ='VIGNETTE']",
                           "//android.widget.TextView[@text ='SHADOWS']",
                           "//android.widget.TextView[@text ='HIGHLIGHTS']",
                           "//android.widget.TextView[@text ='GRAIN']"]